version: '3.8'

services:
  dronedashboard:
    image: ghcr.io/${DOCKER_USERNAME}/dronedashboard:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:1880"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s    
    volumes:
      # Mount the flows and settings to allow for changes without rebuilding
      - ./nodered/flows.json:/data/flows.json
      - ./nodered/settings.js:/data/settings.js
      # You can also mount a local folder for logs
      - ./logs:/data/logs
    depends_on:
      - mqtt-broker
    networks:
      - proxy
    labels:

      - "traefik.enable=true"
      
      # HTTPS router (основной)
      - "traefik.http.routers.dronedashboard.rule=Host(`dronedashboard.site`)"
      - "traefik.http.routers.dronedashboard.entrypoints=https"
      - "traefik.http.routers.dronedashboard.tls=true"
      - "traefik.http.routers.dronedashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dronedashboard.service=dronedashboard"
      
      # HTTP router (редирект на HTTPS)
      - "traefik.http.routers.dronedashboard-insecure.rule=Host(`dronedashboard.site`)"
      - "traefik.http.routers.dronedashboard-insecure.entrypoints=http"
      - "traefik.http.routers.dronedashboard-insecure.middlewares=https-redirect"
      - "traefik.http.routers.dronedashboard-insecure.service=dronedashboard@docker"
      
      # Service definition
      - "traefik.http.services.dronedashboard.loadbalancer.server.port=1880"
      
      # Middleware для редиректа HTTP -> HTTPS
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

      # Middleware для WebSocket
      - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Connection=Upgrade"
      
      # Применяем middleware к WebSocket роутеру
      - "traefik.http.routers.dronedashboard.middlewares=ws-headers"  


      
      

  emulator:
    image: ghcr.io/${DOCKER_USERNAME}/dronedashboard-emulator:latest
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    networks:
      - proxy

  mqtt-broker:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - proxy

networks:
  proxy:
    external: true
