name: Docker Publish and Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: Extract metadata for dronedashboard image
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dronedashboard
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push dronedashboard (backend) image
        uses: docker/build-push-action@v5
        with:
          context: ./backend_ws
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      - name: Extract metadata for dronecan_bridge image
        id: meta_bridge
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dronedashboard-dronecan-bridge
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push dronecan_bridge image
        uses: docker/build-push-action@v5
        with:
          context: ./dronecan_bridge
          push: true
          tags: ${{ steps.meta_bridge.outputs.tags }}
          labels: ${{ steps.meta_bridge.outputs.labels }}

      - name: Extract metadata for Emulator image
        id: meta_emulator
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/dronedashboard-emulator
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Emulator image
        uses: docker/build-push-action@v5
        with:
          context: ./emulator
          push: true
          tags: ${{ steps.meta_emulator.outputs.tags }}
          labels: ${{ steps.meta_emulator.outputs.labels }}

  deploy:
    needs: build_and_push
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force stop and remove old containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 2222
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/dronedashboard || exit 0
            docker compose -f docker-compose.prod.yml down || exit 0

      - name: Clean mosquitto directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 2222
          script: |
            sudo rm -rf /home/${{ secrets.REMOTE_USER }}/dronedashboard/mosquitto

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 2222
          source: "docker-compose.prod.yml,deploy.sh,mosquitto/"
          target: "/home/${{ secrets.REMOTE_USER }}/dronedashboard"
          overwrite: true

      - name: Set ownership and permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 2222
          script: |
            sudo chown -R 1883:1883 /home/${{ secrets.REMOTE_USER }}/dronedashboard/mosquitto/config
            sudo chmod -R a+rX /home/${{ secrets.REMOTE_USER }}/dronedashboard/mosquitto/config

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 2222
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/dronedashboard
            chmod +x deploy.sh
            ./deploy.sh ${{ github.repository_owner }}